compile_all: part1.java part2.java part2_2.java
	javac part1.java
	javac part2.java
	javac part2_2.java

part1: part1.java
	java part1

part2: part2.java
	java part2

part2_2: part2_2.java
	java part2_2

clean:
	rm *.class
